# Generated by Django 4.1.6 on 2023-03-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='cantmaterias',
            new_name='cantMaterias',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='user',
        ),
        migrations.AlterField(
            model_name='semestre',
            name='promedio',
            field=models.IntegerField(),
        ),
    ]
